#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
高性能CSV数据导入PostgreSQL脚本
包含数据校验、去重、历史记录等功能
"""

import csv
import glob
import json
import os
import re
import time
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Tuple

import psycopg2
from psycopg2.extras import RealDictCursor, execute_batch, execute_values

from carinfo.utils import parse_price

# 北京时间时区
BEIJING_TZ = timezone(timedelta(hours=8))


def now_beijing():
    """获取当前北京时间"""
    return datetime.now(BEIJING_TZ)


# 加载环境变量
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # 如果没有python-dotenv，使用系统环境变量


class DataValidator:
    """数据校验器"""
    
    @staticmethod
    def validate_vehicle_id(vehicle_id: str) -> Tuple[bool, str]:
        """验证车辆ID"""
        if not vehicle_id or vehicle_id.strip() == '':
            return False, "车辆ID不能为空"
        if len(vehicle_id) > 100:
            return False, "车辆ID过长"
        return True, ""
    
    @staticmethod
    def validate_price(price_str: str) -> Tuple[bool, str]:
        """验证价格格式"""
        if not price_str:
            return True, ""  # 价格可以为空
        
        price_str = str(price_str).replace('HKD$', '').replace('HKD', '').strip()
        
        if '[' in price_str and '原價' in price_str:
            current_part = price_str.split('[')[0].strip()
            original_part = price_str.split('原價')[1].split(']')[0].strip()
            
            current_clean = current_part.replace(',', '').replace('$', '').strip()
            original_clean = original_part.replace(',', '').replace('$', '').strip()
            
            try:
                current = float(current_clean) if current_clean else None
                original = float(original_clean) if original_clean else None
                if current is not None and current < 0:
                    return False, f"价格不能为负数: {price_str}"
            except ValueError:
                return False, f"价格格式无效: {price_str}"
        else:
            clean = price_str.replace(',', '').replace('$', '').strip()
            try:
                price = float(clean) if clean else None
                if price is not None and price < 0:
                    return False, f"价格不能为负数: {price_str}"
            except ValueError:
                return False, f"价格格式无效: {price_str}"
        
        return True, ""
    
    @staticmethod
    def validate_phone(phone: str) -> Tuple[bool, str]:
        """验证电话号码"""
        if not phone:
            return True, ""  # 电话可以为空
        
        phone = str(phone).strip()
        if not re.match(r'^\d{8}$', phone):
            return False, f"电话号码格式无效: {phone}"
        return True, ""
    
    @staticmethod
    def validate_year(year: str) -> Tuple[bool, str]:
        """验证年份"""
        if not year:
            return True, ""  # 年份可以为空
        
        try:
            year_val = int(year)
            current_year = now_beijing().year
            if year_val < 1900 or year_val > current_year + 1:
                return False, f"年份超出合理范围: {year_val}"
        except ValueError:
            return False, f"年份格式无效: {year}"
        return True, ""
    
    @staticmethod
    def validate_seats(seats: str) -> Tuple[bool, str]:
        """验证座位数"""
        if not seats:
            return True, ""
        
        try:
            seats_val = int(seats)
            if seats_val < 1 or seats_val > 50:
                return False, f"座位数超出合理范围: {seats}"
        except ValueError:
            return False, f"座位数格式无效: {seats}"
        return True, ""
    
    def validate_row(self, row: dict) -> List[str]:
        """验证整行数据"""
        errors = []
        
        valid, msg = self.validate_vehicle_id(row.get('vehicle_id', ''))
        if not valid:
            errors.append(msg)
        
        valid, msg = self.validate_price(row.get('price', ''))
        if not valid:
            errors.append(msg)
        
        valid, msg = self.validate_phone(row.get('phone_number', ''))
        if not valid:
            errors.append(msg)
        
        valid, msg = self.validate_year(row.get('year', ''))
        if not valid:
            errors.append(msg)
        
        valid, msg = self.validate_seats(row.get('seats', ''))
        if not valid:
            errors.append(msg)
        
        return errors


class ImportHistory:
    """导入历史记录"""
    
    def __init__(self, db_connection):
        self.connection = db_connection
        self._ensure_table()
    
    def _ensure_table(self):
        """确保历史记录表存在"""
        try:
            cursor = self.connection.cursor()
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS import_history (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    import_date DATE NOT NULL,
                    import_time TIME NOT NULL,
                    file_name VARCHAR(255) NOT NULL,
                    total_records INT,
                    new_records INT,
                    updated_records INT,
                    skipped_records INT,
                    error_count INT,
                    duration_seconds REAL,
                    status VARCHAR(20),
                    error_details TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_import_date
                ON import_history (import_date)
            """)
            self.connection.commit()
            cursor.close()
        except Exception as e:
            print(f"创建历史记录表失败: {e}")
    
    def record_import(self, file_name: str, total: int, new: int, updated: int, 
                     skipped: int, errors: int, duration: float, status: str, 
                     error_details: str = None):
        """记录导入历史"""
        try:
            cursor = self.connection.cursor()
            now = now_beijing()
            sql = """
                INSERT INTO import_history 
                (import_date, import_time, file_name, total_records, new_records, 
                 updated_records, skipped_records, error_count, duration_seconds, 
                 status, error_details)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            cursor.execute(sql, (
                now.date(), now.time(), file_name, total, new, updated,
                skipped, errors, duration, status, error_details
            ))
            self.connection.commit()
            cursor.close()
            return True
        except Exception as e:
            print(f"记录导入历史失败: {e}")
            return False
    
    def get_recent_history(self, days: int = 7) -> List[Dict]:
        """获取最近的导入历史"""
        try:
            cursor = self.connection.cursor(cursor_factory=RealDictCursor)
            sql = """
                SELECT * FROM import_history
                WHERE import_date >= CURRENT_DATE - (%s)::int
                ORDER BY import_date DESC, import_time DESC
            """
            cursor.execute(sql, (days,))
            results = cursor.fetchall()
            cursor.close()
            return results
        except Exception as e:
            print(f"获取导入历史失败: {e}")
            return []


class CrawlLogManager:
    """爬取日志管理器"""

    def __init__(self, connection):
        self.connection = connection

    def _ensure_table(self):
        """确保爬取日志表存在"""
        try:
            cursor = self.connection.cursor()
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS crawl_logs (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    crawl_date DATE NOT NULL,
                    crawl_time TIME NOT NULL,
                    vehicle_type VARCHAR(50),
                    pages_scraped INT DEFAULT 0,
                    total_vehicles INT DEFAULT 0,
                    new_vehicles INT DEFAULT 0,
                    updated_vehicles INT DEFAULT 0,
                    skipped_vehicles INT DEFAULT 0,
                    proxy_used_count INT DEFAULT 0,
                    proxy_fail_count INT DEFAULT 0,
                    anti_crawler_triggered INT DEFAULT 0,
                    error_count INT DEFAULT 0,
                    crawl_duration_seconds REAL DEFAULT 0,
                    import_duration_seconds REAL DEFAULT 0,
                    total_duration_seconds REAL DEFAULT 0,
                    status VARCHAR(20) DEFAULT 'success',
                    error_details TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_crawl_date
                ON crawl_logs (crawl_date)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_crawl_vehicle_type
                ON crawl_logs (vehicle_type)
            """)
            self.connection.commit()
            cursor.close()
        except Exception as e:
            print(f"创建爬取日志表失败: {e}")

    def record_crawl(self, vehicle_type: str, pages_scraped: int, total_vehicles: int,
                    new_vehicles: int, updated_vehicles: int, skipped_vehicles: int,
                    proxy_used_count: int, proxy_fail_count: int, anti_crawler_triggered: int,
                    error_count: int, crawl_duration: float, import_duration: float,
                    status: str, error_details: str = None):
        """记录爬取日志"""
        try:
            cursor = self.connection.cursor()
            now = now_beijing()
            sql = """
                INSERT INTO crawl_logs (
                    crawl_date, crawl_time, vehicle_type, pages_scraped,
                    total_vehicles, new_vehicles, updated_vehicles, skipped_vehicles,
                    proxy_used_count, proxy_fail_count, anti_crawler_triggered,
                    error_count, crawl_duration_seconds, import_duration_seconds,
                    total_duration_seconds, status, error_details
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            cursor.execute(sql, (
                now.date(), now.time(), vehicle_type, pages_scraped,
                total_vehicles, new_vehicles, updated_vehicles, skipped_vehicles,
                proxy_used_count, proxy_fail_count, anti_crawler_triggered,
                error_count, crawl_duration, import_duration,
                crawl_duration + import_duration, status, error_details
            ))
            self.connection.commit()
            cursor.close()
            return True
        except Exception as e:
            print(f"记录爬取日志失败: {e}")
            return False


def record_crawl_log(db_importer, stats: dict) -> bool:
    """把一次爬取统计写入 crawl_logs（连接不可用时跳过，不影响主流程）。

    stats 键：vehicle_type_name / pages_scraped / total_vehicles / new_vehicles /
    updated_vehicles / error_count / proxy_used_count / proxy_fail_count /
    anti_crawler_triggered / crawl_duration / import_duration / status
    """
    if getattr(db_importer, 'connection', None) is None:
        print("[WARN] 无数据库连接，跳过爬取日志记录")
        return False
    try:
        mgr = CrawlLogManager(db_importer.connection)
        mgr._ensure_table()
        return mgr.record_crawl(
            vehicle_type=stats['vehicle_type_name'],
            pages_scraped=stats['pages_scraped'],
            total_vehicles=stats['total_vehicles'],
            new_vehicles=stats['new_vehicles'],
            updated_vehicles=stats['updated_vehicles'],
            skipped_vehicles=0,
            proxy_used_count=stats['proxy_used_count'],
            proxy_fail_count=stats['proxy_fail_count'],
            anti_crawler_triggered=stats['anti_crawler_triggered'],
            error_count=stats['error_count'],
            crawl_duration=stats['crawl_duration'],
            import_duration=stats['import_duration'],
            status=stats.get('status', 'success'),
        )
    except Exception as e:
        print(f"[WARN] 记录爬取日志失败: {e}")
        return False


class FastCSVImporter:
    def __init__(self):
        """初始化数据库连接"""
        self.connection = None
        self.cursor = None
        self.validator = DataValidator()
        self.history = None
        
    def connect(self):
        """连接数据库"""
        print("正在连接数据库...")
        try:
            # 从环境变量读取配置
            db_config = {
                'host': os.environ.get('DB_HOST', 'localhost'),
                'user': os.environ.get('DB_USER', 'root'),
                'password': os.environ.get('DB_PASSWORD', ''),
                'dbname': os.environ.get('DB_NAME', 'car_info_db'),
                'port': int(os.environ.get('DB_PORT', 5432))
            }

            if not db_config['password']:
                print("[ERROR] 数据库密码未配置，请检查环境变量 DB_PASSWORD")
                return False

            print(f"连接到 {db_config['host']}:{db_config['port']}")

            self.connection = psycopg2.connect(
                host=db_config['host'],
                user=db_config['user'],
                password=db_config['password'],
                dbname=db_config['dbname'],
                port=db_config['port'],
                connect_timeout=30,
                # 防链路静默卡死：入库事务正常亚秒完成，60 秒兜底足够宽裕
                keepalives=1,
                keepalives_idle=30,
                keepalives_interval=10,
                keepalives_count=3,
                options="-c statement_timeout=60000",
            )
            # psycopg2 默认 autocommit=False，事务由 import_rows 显式提交
            self.cursor = self.connection.cursor()

            self.connection.commit()
            print("[OK] 数据库连接成功")
            return True
        except Exception as e:
            print(f"[ERROR] 数据库连接失败: {e}")
            return False
    
    def get_existing_ids(self, vehicle_ids):
        """批量获取已存在的车辆ID"""
        if not vehicle_ids:
            return set()
            
        existing_ids = set()
        batch_size = 10000  # 增加批次大小
        
        for i in range(0, len(vehicle_ids), batch_size):
            batch = vehicle_ids[i:i + batch_size]
            placeholders = ','.join(['%s'] * len(batch))
            query = f"SELECT vehicle_id FROM vehicles WHERE vehicle_id IN ({placeholders})"
            self.cursor.execute(query, batch)
            existing_ids.update(row[0] for row in self.cursor.fetchall())
            
        return existing_ids

    def clean_data(self, value):
        """清理数据"""
        if value is None or value == '':
            return ''
        str_value = str(value).strip()
        if str_value.endswith('.0'):
            return str_value[:-2]
        return str_value
    
    def import_csv(self, csv_file):
        """导入单个CSV文件（手动/独立通道：读CSV后走 import_rows）"""
        if not os.path.exists(csv_file):
            print(f"[ERROR] 文件不存在: {csv_file}")
            return False

        print(f"\n开始导入: {csv_file}")

        try:
            # 读取CSV数据
            with open(csv_file, 'r', encoding='utf-8-sig') as f:
                data = list(csv.DictReader(f))

            if not data:
                print("[ERROR] CSV文件为空")
                return False

            print(f"读取到 {len(data)} 条记录")

            # 检查必要字段
            if 'vehicle_id' not in data[0] or 'sale_status' not in data[0]:
                print("[ERROR] CSV文件缺少必要字段 (vehicle_id, sale_status)")
                return False

            # 获取车辆类型
            filename = os.path.basename(csv_file)
            vehicle_type = 3  # 默认类型
            if 'car_data_' in filename:
                try:
                    vehicle_type = int(filename.split('_')[2].split('.')[0])
                except:
                    pass

            return self.import_rows(data, vehicle_type)

        except Exception as e:
            print(f"[ERROR] 导入失败: {e}")
            if self.connection:
                self.connection.rollback()
            return False

    def _ensure_connection(self) -> bool:
        """确保数据库连接可用（懒连接 + 断线重连），供逐页直接入库复用。"""
        if self.connection is not None and self.connection.closed == 0:
            try:
                # psycopg2 无 ping，用一次轻量探测判断连接死活
                probe = self.connection.cursor()
                probe.execute("SELECT 1")
                probe.close()
                return True
            except psycopg2.Error:
                print("[WARN] 数据库连接已断开，尝试重连...")
                try:
                    self.connection.close()
                except Exception:
                    pass
                self.connection = None
                self.cursor = None
        return self.connect()

    def _insert_counted(self, sql: str, rows: list, page_size: int = 1000) -> int:
        """execute_values 分块插入并累计真实写入行数。

        execute_values 一次传超过 page_size 行会拆成多条语句，而 cursor.rowcount
        只反映最后一条，这里按 page_size 切块保证每次恰好一条语句、计数准确。
        """
        total = 0
        for i in range(0, len(rows), page_size):
            execute_values(self.cursor, sql, rows[i:i + page_size],
                           page_size=page_size)
            total += max(self.cursor.rowcount, 0)
        return total

    def import_rows(self, rows: List[dict], vehicle_type: int) -> dict:
        """把内存行直接写入数据库（爬取主通道，CSV 备份之外的正路）。

        新车辆 INSERT IGNORE，已存在车辆分批全字段 UPDATE，图片仅补新车辆。
        返回 {"success", "new", "updated", "errors", "duration"}。
        """
        started = time.time()
        if not rows:
            return {"success": True, "new": 0, "updated": 0, "errors": 0, "duration": 0.0}

        if not self._ensure_connection():
            return {"success": False, "new": 0, "updated": 0, "errors": len(rows), "duration": 0.0}

        try:
            # 获取已存在的ID
            print(f"[{now_beijing().strftime('%H:%M:%S')}] 开始查询已存在的车辆ID...")
            start_query = time.time()
            vehicle_ids = [row.get('vehicle_id', '') for row in rows]
            existing_ids = self.get_existing_ids(vehicle_ids)
            query_time = time.time() - start_query
            print(f"[{now_beijing().strftime('%H:%M:%S')}] 查询完成，发现 {len(existing_ids)} 个已存在的记录，耗时 {query_time:.2f} 秒")

            # 准备数据
            print(f"[{now_beijing().strftime('%H:%M:%S')}] 开始准备数据...")
            start_prepare = time.time()
            new_vehicles = []
            update_vehicles = []
            list_only_updates = []   # 兜底行 + 已存在 → 只补列表页可靠字段，不覆盖详情字段
            new_images = []

            for row in rows:
                vehicle_id = row.get('vehicle_id', '')
                if not vehicle_id:
                    continue

                # 解析价格
                current_price, original_price = parse_price(row.get('price', ''))

                # 处理状态
                vehicle_status = 2 if row.get('sale_status', '未售') == '已售' else 1

                # 处理扩展字段：爬虫给的可能是 dict（内部直传）或 JSON 字符串（CSV 回放）。
                # 两种都要认 —— 旧实现写死 json.loads()，传 dict 会抛 TypeError 被下面的
                # 裸 except 静默吞掉，extra_fields 变 None、list_only 标记随之丢失，
                # 兜底行就退化成了全字段 UPDATE（详情数据被空值冲掉）。
                extra_fields = None
                raw_extra = row.get('extra_fields')
                if raw_extra:
                    if isinstance(raw_extra, dict):
                        extra_fields = raw_extra
                    else:
                        try:
                            extra_fields = json.loads(raw_extra)
                        except (TypeError, ValueError):
                            extra_fields = None

                # 兜底行判据：详情页解析失败时 car28._build_fallback_car 只填了列表页字段，
                # 把 list_only 标记写进 extra_fields。**这个标记必须在这里消费** ——
                # 否则下面的全字段 UPDATE 会用空 description / 空联系人 / 窄 extra_fields
                # 覆盖掉老车已经攒下的详情数据（且掉出爬取范围后永远补不回来）。
                is_list_only = bool(
                    isinstance(extra_fields, dict) and extra_fields.get('list_only')
                )

                # 准备车辆数据
                vehicle_data = (
                    vehicle_id, vehicle_type, vehicle_status,
                    int(row.get('page_number', 1)),
                    self.clean_data(row.get('car_number')),
                    row.get('car_url', ''),
                    row.get('car_category', ''),
                    row.get('car_brand', ''),
                    row.get('car_model', ''),
                    row.get('fuel_type', ''),
                    self.clean_data(row.get('seats')),
                    row.get('engine_volume', ''),
                    row.get('transmission', ''),
                    self.clean_data(row.get('year')),
                    row.get('description', ''),
                    row.get('price', ''),
                    current_price, original_price,
                    row.get('contact_info', ''),
                    row.get('update_date', ''),
                    json.dumps(extra_fields) if extra_fields else None,
                    row.get('contact_name', ''),
                    self.clean_data(row.get('phone_number'))
                )

                if vehicle_id in existing_ids:
                    if is_list_only:
                        # 老车 + 兜底行：只更新列表页可靠的字段（价格/状态/页码/网址）。
                        # 详情专属字段（description/联系人/电话/extra_fields/车类）一律不动，
                        # 保住库里已有的优质数据。
                        list_only_updates.append((
                            vehicle_status,
                            int(row.get('page_number', 1)),
                            row.get('car_url', ''),
                            row.get('price', ''),
                            current_price,
                            original_price,
                            vehicle_id,
                        ))
                    else:
                        update_vehicles.append(vehicle_data)
                else:
                    new_vehicles.append(vehicle_data)

                    # 只为新车辆处理图片
                    image_urls = row.get('image_urls', '').split('\n') if row.get('image_urls') else []
                    for i, url in enumerate(image_urls):
                        url = url.strip()
                        if url:
                            new_images.append((vehicle_id, url, i))

            prepare_time = time.time() - start_prepare
            print(f"[{now_beijing().strftime('%H:%M:%S')}] 数据准备完成，新增: {len(new_vehicles)} 条，更新: {len(update_vehicles)} 条，"
                  f"兜底仅补列表字段: {len(list_only_updates)} 条，图片: {len(new_images)} 条，耗时 {prepare_time:.2f} 秒")

            # 执行批量操作
            start_time = now_beijing()
            print(f"[{start_time.strftime('%H:%M:%S')}] 开始执行数据库操作...")

            # 插入新车辆
            inserted_count = 0
            if new_vehicles:
                print(f"[{now_beijing().strftime('%H:%M:%S')}] 正在插入 {len(new_vehicles)} 条新车辆记录...")
                start_insert = time.time()
                insert_sql = """
                INSERT INTO vehicles (
                    vehicle_id, vehicle_type, vehicle_status, page_number,
                    car_number, car_url, car_category, car_brand, car_model,
                    fuel_type, seats, engine_volume, transmission, year,
                    description, price, current_price, original_price,
                    contact_info, update_date, extra_fields, contact_name, phone_number
                ) VALUES %s
                ON CONFLICT (vehicle_id) DO NOTHING
                """

                # 一次性插入所有新车辆；rowcount 取实际写入行数：
                # 冲突被跳过的行不该算作"新增"
                inserted_count = self._insert_counted(insert_sql, new_vehicles)
                self.connection.commit()
                insert_time = time.time() - start_insert
                print(f"[{now_beijing().strftime('%H:%M:%S')}] [OK] 新增 {inserted_count} 条车辆记录"
                      f"（候选 {len(new_vehicles)} 条），耗时 {insert_time:.2f} 秒")

            # 更新现有车辆（直接操作数据库）
            success_update_count = 0
            error_update_count = 0
            if update_vehicles:
                print(f"[{now_beijing().strftime('%H:%M:%S')}] 正在更新 {len(update_vehicles)} 条车辆记录...")

                start_update = time.time()

                # 分批处理，每次100条
                batch_size = 100
                total_batches = (len(update_vehicles) + batch_size - 1) // batch_size

                for batch_num in range(total_batches):
                    start_idx = batch_num * batch_size
                    end_idx = min(start_idx + batch_size, len(update_vehicles))
                    batch_vehicles = update_vehicles[start_idx:end_idx]

                    print(f"[{now_beijing().strftime('%H:%M:%S')}] 处理批次 {batch_num + 1}/{total_batches}，{len(batch_vehicles)} 条记录...")

                    try:
                        self._update_via_database(batch_vehicles)
                        success_update_count += len(batch_vehicles)
                        print(f"[{now_beijing().strftime('%H:%M:%S')}] [OK] 批次 {batch_num + 1} 完成: 成功 {len(batch_vehicles)}, 失败 0")
                    except Exception as e:
                        error_update_count += len(batch_vehicles)
                        print(f"[{now_beijing().strftime('%H:%M:%S')}] [ERROR] 批次 {batch_num + 1} 更新失败: {e}")

                update_time = time.time() - start_update
                print(f"[{now_beijing().strftime('%H:%M:%S')}] [OK] 数据库更新完成: 成功 {success_update_count}, 失败 {error_update_count}, 总耗时 {update_time:.2f} 秒")

            # 兜底行（list_only）+ 已存在：只补列表页可靠字段，**绝不碰详情字段**
            if list_only_updates:
                print(f"[{now_beijing().strftime('%H:%M:%S')}] 正在为 {len(list_only_updates)} 条兜底记录补齐列表页字段"
                      f"（保留已有详情数据）...")
                start_lo = time.time()
                try:
                    self._update_list_only(list_only_updates)
                    print(f"[{now_beijing().strftime('%H:%M:%S')}] [OK] 兜底记录已补列表字段"
                          f"（详情字段保持不变），耗时 {time.time() - start_lo:.2f} 秒")
                except Exception as e:
                    error_update_count += len(list_only_updates)
                    print(f"[{now_beijing().strftime('%H:%M:%S')}] [ERROR] 兜底记录更新失败: {e}")

            # 插入图片（仅新车辆，更新车辆不处理图片）
            if new_images:
                print(f"[{now_beijing().strftime('%H:%M:%S')}] 正在插入 {len(new_images)} 条图片记录（仅新车辆）...")
                start_images = time.time()
                image_sql = """
                INSERT INTO vehicle_images (vehicle_id, image_url, image_order)
                VALUES %s ON CONFLICT DO NOTHING
                """
                self._insert_counted(image_sql, new_images)
                self.connection.commit()
                images_time = time.time() - start_images
                print(f"[{now_beijing().strftime('%H:%M:%S')}] [OK] 新增 {len(new_images)} 条图片记录，耗时 {images_time:.2f} 秒")
            else:
                print(f"[{now_beijing().strftime('%H:%M:%S')}] 无需处理图片（无新车辆）")

            # 计算耗时
            end_time = now_beijing()
            duration = (end_time - start_time).total_seconds()
            print(f"[OK] 导入完成！总计处理 {len(rows)} 条记录，耗时 {duration:.1f} 秒")
            return {
                "success": True,
                "new": inserted_count,
                "updated": success_update_count,
                "errors": error_update_count,
                "duration": time.time() - started
            }

        except Exception as e:
            print(f"[ERROR] 导入失败: {e}")
            if self.connection:
                self.connection.rollback()
            return {
                "success": False,
                "new": 0,
                "updated": 0,
                "errors": len(rows),
                "duration": time.time() - started
            }

    def import_all_csv(self):
        """导入所有CSV文件"""
        csv_files = glob.glob("data/csv/car_data_*.csv")
        if not csv_files:
            print("[ERROR] 未找到任何 data/csv/car_data_*.csv 文件")
            return {
                "success_count": 0,
                "total_files": 0,
                "total_new": 0,
                "total_updated": 0,
                "total_errors": 0
            }
        
        print(f"找到 {len(csv_files)} 个CSV文件")
        for csv_file in csv_files:
            print(f"- {csv_file}")
        
        success_count = 0
        total_new = 0
        total_updated = 0
        total_errors = 0
        start_time = now_beijing()
        
        for csv_file in csv_files:
            result = self.import_csv(csv_file)
            if result and result.get("success"):
                success_count += 1
            
            if result:
                total_new += result.get("new", 0)
                total_updated += result.get("updated", 0)
                total_errors += result.get("errors", 0)
        
        end_time = now_beijing()
        duration = (end_time - start_time).total_seconds()
        
        print(f"\n=== 导入完成 ===")
        print(f"成功导入: {success_count}/{len(csv_files)} 个文件")
        print(f"总耗时: {duration:.1f} 秒")
        
        return {
            "success_count": success_count,
            "total_files": len(csv_files),
            "total_new": total_new,
            "total_updated": total_updated,
            "total_errors": total_errors
        }
    
    def show_stats(self):
        """显示统计信息"""
        try:
            self.cursor.execute("SELECT COUNT(*) FROM vehicles")
            total_vehicles = self.cursor.fetchone()[0]
            
            self.cursor.execute("SELECT COUNT(*) FROM vehicle_images")
            total_images = self.cursor.fetchone()[0]
            
            self.cursor.execute("""
                SELECT vehicle_status, COUNT(*) 
                FROM vehicles 
                GROUP BY vehicle_status
            """)
            status_stats = self.cursor.fetchall()
            
            print(f"\n=== 数据库统计 ===")
            print(f"总车辆数: {total_vehicles:,}")
            print(f"总图片数: {total_images:,}")
            
            for status, count in status_stats:
                status_name = "已售" if status == 2 else "未售"
                print(f"{status_name}: {count:,} 辆")
                
        except Exception as e:
            print(f"[ERROR] 获取统计失败: {e}")
    
    def _update_list_only(self, records):
        """兜底行专用更新：只写列表页可靠的字段。

        为什么单独一条 SQL，不复用 `_update_via_database`：
        兜底行的 description / contact_info / contact_name / phone_number / extra_fields
        都是**空值占位**（car28._build_fallback_car 只填列表页字段）。走全字段 UPDATE 会把
        这辆老车此前攒下的详情数据整行抹掉，而它一旦掉出抓取范围就再也补不回来。
        这里只更新「列表页确实有、且详情页不产出」的字段，详情字段原样保留。

        记录元组顺序：(vehicle_status, page_number, car_url, price,
                      current_price, original_price, vehicle_id)
        """
        sql = """
        UPDATE vehicles SET
            vehicle_status = %s, page_number = %s, car_url = %s,
            price = %s, current_price = %s, original_price = %s,
            updated_at = CURRENT_TIMESTAMP
        WHERE vehicle_id = %s
        """
        execute_batch(self.cursor, sql, records, page_size=100)
        self.connection.commit()

    def _update_via_database(self, batch_vehicles):
        """数据库更新方案 - 更新所有字段"""
        try:
            update_sql = """
            UPDATE vehicles SET
                vehicle_type = %s, vehicle_status = %s, page_number = %s,
                car_number = %s, car_url = %s, car_category = %s, car_brand = %s, car_model = %s,
                fuel_type = %s, seats = %s, engine_volume = %s, transmission = %s, year = %s,
                description = %s, price = %s, current_price = %s, original_price = %s,
                contact_info = %s, update_date = %s, extra_fields = %s,
                contact_name = %s, phone_number = %s,
                updated_at = CURRENT_TIMESTAMP
            WHERE vehicle_id = %s
            """

            update_data = []
            for vehicle_data in batch_vehicles:
                # 字段顺序（与 vehicle_data 元组下标对应，勿随意调整）:
                # vehicle_type, vehicle_status, page_number, car_number, car_url,
                # car_category, car_brand, car_model, fuel_type, seats, engine_volume,
                # transmission, year, description, price, current_price, original_price,
                # contact_info, update_date, extra_fields, contact_name, phone_number, vehicle_id
                record = (
                    vehicle_data[1],   # vehicle_type
                    vehicle_data[2],   # vehicle_status
                    vehicle_data[3],   # page_number
                    vehicle_data[4],   # car_number
                    vehicle_data[5],   # car_url
                    vehicle_data[6],   # car_category
                    vehicle_data[7],   # car_brand
                    vehicle_data[8],   # car_model
                    vehicle_data[9],   # fuel_type
                    vehicle_data[10],  # seats
                    vehicle_data[11],  # engine_volume
                    vehicle_data[12],  # transmission
                    vehicle_data[13],  # year
                    vehicle_data[14],  # description
                    vehicle_data[15],  # price
                    vehicle_data[16],  # current_price
                    vehicle_data[17],  # original_price
                    vehicle_data[18],  # contact_info
                    vehicle_data[19],  # update_date
                    vehicle_data[20],  # extra_fields
                    vehicle_data[21],  # contact_name
                    vehicle_data[22],  # phone_number
                    vehicle_data[0]     # vehicle_id (WHERE条件)
                )
                update_data.append(record)

            execute_batch(self.cursor, update_sql, update_data, page_size=100)
            self.connection.commit()

        except Exception as e:
            print(f"数据库更新失败: {e}")
            if self.connection:
                self.connection.rollback()
            # 必须向上抛：调用方靠异常把该批次计入 error_update_count，
            # 吞掉异常会让失败批次被记成成功，爬取日志统计失真
            raise
    
    def close(self):
        """关闭连接"""
        if self.cursor:
            self.cursor.close()
        if self.connection:
            self.connection.close()
        print("[OK] 数据库连接已关闭")

def main():
    """手动补导通道：把 data/csv/*.csv 回灌数据库。

    爬取主通道已改为逐页直接入库（car28.scrape_vehicle_type → import_rows），
    本入口只在补导/审计时使用，没有爬取统计可用，因此不再写 crawl_logs。
    """
    # 确保输出编码正确
    import sys
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    if hasattr(sys.stderr, 'reconfigure'):
        sys.stderr.reconfigure(encoding='utf-8')

    print("=== CSV 补导工具 ===")
    print("用途: 把 data/csv/car_data_*.csv 回灌 PostgreSQL（爬取主通道不走这里）")

    importer = FastCSVImporter()

    if not importer.connect():
        return

    import_start_time = now_beijing()

    try:
        # 初始化历史记录
        importer.history = ImportHistory(importer.connection)

        # 检查CSV文件
        csv_files = glob.glob("data/csv/car_data_*.csv")
        if not csv_files:
            print("\n[ERROR] data/csv/ 目录下没有找到 car_data_*.csv 文件")
            return

        print(f"\n找到 {len(csv_files)} 个CSV文件:")
        for f in csv_files:
            print(f"  - {f}")

        # 记录每个文件的导入结果
        total_new = 0
        total_updated = 0
        total_errors = 0

        # 直接开始导入
        print("\n开始自动导入...")
        import_result = importer.import_all_csv()
        if import_result:
            total_new = import_result.get("total_new", 0)
            total_updated = import_result.get("total_updated", 0)
            total_errors = import_result.get("total_errors", 0)

        # 显示统计
        importer.show_stats()

        # 补导耗时
        import_duration = (now_beijing() - import_start_time).total_seconds()
        print(f"\n=== 补导完成，耗时 {import_duration:.1f} 秒 ===")
        print(f"新增 {total_new}，更新 {total_updated}，错误 {total_errors}")

    finally:
        importer.close()

if __name__ == "__main__":
    main()
